### ISSUE TITLE
wgc auth login gives a error

### ISSUE THREAD

**Issue by anudeepsripathi** [wundergraph/cosmo#940] opened 2024-07-17 09:01 UTC
### Component(s)

cli

### Component version

0.58.4

### wgc version

0.58.4

### controlplane version

0.58.4

### router version

0.58.4

### What happened?

When I run wgc auth login cmd I get the below errors from my PC after I authorize cosmos from browser:

Opening browser for login...

WunderGraph Cosmo
Device Login Successful
You may close this browser window and go back to your device.

TypeError: Cannot read properties of undefined (reading 'map')
    at Command.<anonymous> (file:///C:/Users/ansri/Downloads/softwares/nvm/v18.17.0/node_modules/wgc/dist/commands/auth/commands/login.js:37:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.parseAsync (C:\Users\ansri\Downloads\softwares\nvm\v18.17.0\node_modules\wgc\node_modules\commander\lib\command.js:936:5)
    at async file:///C:/Users/ansri/Downloads/softwares/nvm/v18.17.0/node_modules/wgc/dist/index.js:8:5
╭────────────────────────────────────────────────────────────────╮
│                                                                │
│   Please try the below steps to solve the issue                │
│                                                                │
│   [1] Upgrade to the latest version:                           │
│       npm i -g wgc@latest                                      │
│   [2] If it persists, please open an issue:                    │
│       https://github.com/wundergraph/cosmo/issues/new/choose   │
│                                                                │
╰────────────────────────────────────────────────────────────────╯

**Comment by Aenimus** [comment] 2024-07-20 14:14
Hi @anudeepsripathi,

I am not able to replicate this `wgc 0.58.5` with node `v20.11.0` nor node `v18.19.1`.

How is your `wgc` installed? And what is the exact command you are typing? E.g.,`wgc auth login` or `npx wgc auth login` or `npx wgc@latest auth login`?

**Comment by anudeepsripathi** [comment] 2024-07-25 11:48
> `v20.11.0` nor node `v18.19.1`.

I have updated my node version to 20.11.0, and added all the exports below as key value pairs in local windows environment variables
 COSMO_API_KEY=cosmo_669b576aaadc10ee1ae81d9193425705
COSMO_API_URL=http://localhost:3001
KC_API_URL=http://localhost:8080
CDN_URL=http://localhost:11000
Still I get the same error after I run these below cmds in sequence in intellij terminal, my cosmos docker is up as well.
 wgc subgraph publish myGraphName \ --namespace default \ --schema ./cosmo \ --label team=<myTeamName>\ --routing-url http://<my-pc-ip>:8080/graphql \ --fail-on-composition-error
Organization slug is not set. Please run `wgc auth login` to set the organization slug.

**Comment by Aenimus** [comment] 2024-08-01 21:26
Hi @anudeepsripathi,

How did you install `wgc`? What does `where wgc` yield?

**Comment by anudeepsripathi** [comment] 2024-08-02 05:35
> │ npm i -g wgc@lates



> Hi @anudeepsripathi,
> 
> How did you install `wgc`? What does `where wgc` yield? 
npm i -g wgc@latest

**Comment by Aenimus** [comment] 2024-08-02 14:03
Hi @anudeepsripathi,

I want to help you, but please try to answer all questions. What does `where wgc` yield? Additionally, what does `wgc --version` yield?

Thanks!

**Comment by anudeepsripathi** [comment] 2024-08-05 04:32
> Hi @anudeepsripathi,
> 
> I want to help you, but please try to answer all questions. What does `where wgc` yield? Additionally, what does `wgc --version` yield?
> 
> Thanks!

where wgc
C:\Program Files\nodejs\wgc
C:\Program Files\nodejs\wgc.cmd

wgc --version
0.58.5

**Comment by Aenimus** [comment] 2024-08-05 08:14
Hi @anudeepsripathi,

Thanks for that. We still cannot replicate on Windows; we tried both Node 18 and 20 (with `nvm`). Can you do the following (in the same order)?

1. `where node`
2. `npm uninstall -g wgc`
3. `where wgc`

If there is still a `wgc` on your path, please remove it. Then please try reinstalling `wgc`.

**Comment by anudeepsripathi** [comment] 2024-08-05 09:34
> Hi @anudeepsripathi,
> 
> Thanks for that. We still cannot replicate on Windows; we tried both Node 18 and 20 (with `nvm`). Can you do the following (in the same order)?
> 
> 1. `where node`
> 2. `npm uninstall -g wgc`
> 3. `where wgc`
> 
> If there is still a `wgc` on your PATH, please remove it. Then please try reinstalling `wgc`.

1. where node
C:\Program Files\nodejs\node.exe
2. >npm uninstall -g wgc
removed 359 packages in 3s
3. where wgc
INFO: Could not find files for the given pattern(s).

**Comment by Aenimus** [comment] 2024-08-05 11:18
Hi @anudeepsripathi,

Is the problem still persisting? Where are you running this command? E.g., cmd, power shell, bash, cmder, etc.

Thanks

**Comment by Aenimus** [comment] 2024-08-06 09:19
Hi @anudeepsripathi,

Are you running everything locally? Or are you using Cosmo Cloud?

If the former, please tell us the accurate versions of everything (controlplane, etc.). Please also make sure everything is properly seeded.

Thanks

**Comment by Aenimus** [comment] 2024-08-13 13:28
Hi @anudeepsripathi,

We are unable to reproduce, and we haven't received any answers to latest our questions.

Closing.

**Closed by Aenimus** 2024-08-13 13:28 UTC
Labels: bug, internally-reviewed, awaiting feedback

**Comment by anudeepsripathi** [comment] 2024-08-14 06:56
> Hi @anudeepsripathi,
> 
> Are you running everything locally? Or are you using Cosmo Cloud?
> 
> If the former, please tell us the accurate versions of everything (controlplane, etc.). Please also make sure everything is properly seeded.
> 
> Thanks

Yes using everything locally using local docker
