### ISSUE TITLE
Router error "Cannot return null for non-nullable field" with unions

### ISSUE THREAD

**Issue by vadimofd** [wundergraph/cosmo#694] opened 2024-04-04 21:12 UTC
### Component(s)

router

### Component version

0.71.2

### wgc version

0.40.0

### controlplane version

cloud

### router version

0.71.2

## Description

Router returns `Cannot return null for non-nullable field` error for a field that's not requested by the client operation.

It appears that union sub-fields that share the same path are implicitly required for all union types with that field even when client operation requests this field only on one of them.

In the following example type `Test` can be `Test1` or `Test2`. Both have field `f` of `TypeX` which has an `id` field. When `Test` is requested by the client with and without the `id` depending on the actual response type, the one without the `id` incorrectly causes router to return an error.

GraphQL Schema
```GraphQL
type TestX {
    id: ID!
    fx: String
}

type Test1 {
    f: TestX
}

type Test2 {
    f: TestX
}

union Test = Test1 | Test2

schema {
  subscription: Subscriptions
}

type Subscriptions {
    test: Test
}
```

GraphQL Operation
```GraphQL
subscription testSub {
  test {
    ... on Test1 {
      f {
        fx
      }
    }
    ... on Test2 {
      f {
        id
        fx
      }
    }
  }
}
```

Subgraph Payload (only `payload` part is shown here). See below for full wscat messages trace.
```JSON
{
    "data": {
        "test": {
            "__typename": "Test1",
            "f": {
                "fx": "v1"
            }
        }
    }
}
```

Router Error Response
```JSON
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field 'Subscription.test.f.id'.",
      "path": [
        "test",
        "f",
        "id"
      ]
    }
  ]
}
```

## Steps to Reproduce

1. Publish `test` sub-graph
  ```wgc subgraph publish test -r http://<subgraph-host>:<subgraph-port>  --schema test.graphqls --label-matcher team=test```
2. Create `test` federated graph that includes the published `test` sub-graph
   ```wgc federated-graph create test -r http://<fedgraph-host>:<fedgraph-port> --label-matcher team=test```
3. Create router token for the federated graph `test`
   ```wgc router token create test -g test```
4. Update router config with the created token
   ```yaml
   configuration:
     graphApiToken: ""
   ```
6. Start `wscat` on sub-graph host and listening to the specified port
   ```wscat -l <subgraph-port>```
7. Using Playground, execute GraphQL Operation from the above description.
8. In the wscat shell session, respond to incoming messages (`<` prefix) with outgoing (`>`) as shown bellow:
```
Client connected
< {"type":"connection_init","payload":{"extensions":{"upgradeHeaders":{"Accept-Language":["en-US,en;q=0.9"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"],"X-Forwarded-For":[REDUCTED],"X-Forwarded-Proto":["https"]},"initialPayload":{"X-WG-TRACE":"true"}}}}
> {"type":"connection_ack"}
< {"type":"start","id":"1","payload":{"query":"subscription{test {__typename ... on Test1 {f {fx}} ... on Test2 {f {id fx}}}}","extensions":{"upgradeHeaders":{"Accept-Language":["en-US,en;q=0.9"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"],"X-Forwarded-For":[REDUCTED],"X-Forwarded-Proto":["https"]},"initialPayload":{"X-WG-TRACE":"true"}}}}
> {"id": "1", "type": "data", "payload": {"data": {"test": {"__typename":"Test1", "f":{"fx":"v1"}}}}}
< {"type":"stop","id":"1"}
Disconnected (code: 1000, reason: "")
```
## Expected Result

Playground should show the following response without the `id` field.

```JSON
{
  "data": {
    "test": {
      "f": {
        "fx": "v1"
      }
    }
  }
}
```

## Actual Result

Playground shows error response indicating missing `id` field which has NOT been requested by the Playground.

```JSON
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field 'Subscription.test.f.id'.",
      "path": [
        "test",
        "f",
        "id"
      ]
    }
  ]
}
```

## Environment

N/A

### Router configuration

```yaml
configuration:
  graphApiToken: "" # federated graph token
```

### Router execution config

```json
schema {
  query: Query
  subscription: Subscription
}

directive @tag(name: String!) repeatable on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | UNION

type TestX {
  id: ID!
  fx: String
}

type Test1 {
  f: TestX
}

type Test2 {
  f: TestX
}

union Test = Test1 | Test2

type Query {
  dummy: String
}

type Subscription {
  test: Test
}
```

### Log output

```shell
Client connected
< {"type":"connection_init","payload":{"extensions":{"upgradeHeaders":{"Accept-Language":["en-US,en;q=0.9"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"],"X-Forwarded-For":[REDUCTED],"X-Forwarded-Proto":["https"]},"initialPayload":{"X-WG-TRACE":"true"}}}}
> {"type":"connection_ack"}
< {"type":"start","id":"1","payload":{"query":"subscription{test {__typename ... on Test1 {f {fx}} ... on Test2 {f {id fx}}}}","extensions":{"upgradeHeaders":{"Accept-Language":["en-US,en;q=0.9"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"],"X-Forwarded-For":[REDUCTED],"X-Forwarded-Proto":["https"]},"initialPayload":{"X-WG-TRACE":"true"}}}}
> {"id": "1", "type": "data", "payload": {"data": {"test": {"__typename":"Test1", "f":{"fx":"v1"}}}}}
< {"type":"stop","id":"1"}
Disconnected (code: 1000, reason: "")
```

**Comment by Aenimus** [comment] 2024-04-09 09:22
Hi,

This looks to be a duplicate of https://github.com/wundergraph/cosmo/issues/679

We're aware of the issue, and we are working on a fix.

Thanks!

**Closed by Aenimus** 2024-04-09 09:22 UTC
Labels: bug
